import { REPORT_PAGE_BASE_CSS } from './reportPageStyle';

// Every report.md in this project is generated by our own buildReportMarkdown()-style functions
// (cost, healing, flaky, traceability, promptVersions), never user-authored - so the markdown
// vocabulary actually in use is small and known: #/##/### headers, "- " bullet lists (with
// **bold** and `code` inline), and "| a | b |" pipe tables with a "|---|---|" separator row.
// A full CommonMark-compliant parser would be overkill (and a new npm dependency) for content
// this constrained - this handles exactly that subset, nothing more.

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// Applied to already-escaped text, so these patterns only ever match the literal markdown
// syntax characters, never anything that came from escaping (&amp; etc. contain no * or `).
function renderInline(escapedText: string): string {
  return escapedText
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
}

function isTableRow(line: string): boolean {
  return line.trim().startsWith('|') && line.trim().endsWith('|');
}

function isTableSeparatorRow(line: string): boolean {
  return isTableRow(line) && /^\|[\s:|-]+\|$/.test(line.trim());
}

function splitTableCells(line: string): string[] {
  return line
    .trim()
    .slice(1, -1)
    .split('|')
    .map((cell) => cell.trim());
}

/**
 * Converts one of this project's generated report.md files into an HTML fragment (not a full
 * page - see wrapReportPage below for that). Exported separately from wrapReportPage so tests can
 * assert on the rendered fragment without needing to parse a full HTML document.
 */
export function renderMarkdownToHtml(markdown: string): string {
  const lines = markdown.split('\n');
  const htmlParts: string[] = [];
  let i = 0;

  while (i < lines.length) {
    const line = lines[i];

    if (line.trim() === '') {
      i++;
      continue;
    }

    const headerMatch = line.match(/^(#{1,3})\s+(.*)$/);
    if (headerMatch) {
      const level = headerMatch[1].length;
      htmlParts.push(`<h${level}>${renderInline(escapeHtml(headerMatch[2]))}</h${level}>`);
      i++;
      continue;
    }

    if (line.startsWith('- ')) {
      const items: string[] = [];
      while (i < lines.length && lines[i].startsWith('- ')) {
        items.push(`<li>${renderInline(escapeHtml(lines[i].slice(2)))}</li>`);
        i++;
      }
      htmlParts.push(`<ul>${items.join('')}</ul>`);
      continue;
    }

    if (isTableRow(line)) {
      const headerCells = splitTableCells(line);
      i++;
      // Every table this project generates has a separator row right after the header (see
      // buildReportMarkdown() in costReport.ts etc.) - skip it rather than rendering it as data.
      if (i < lines.length && isTableSeparatorRow(lines[i])) i++;
      const bodyRows: string[] = [];
      while (i < lines.length && isTableRow(lines[i])) {
        const cells = splitTableCells(lines[i]);
        bodyRows.push(`<tr>${cells.map((c) => `<td>${renderInline(escapeHtml(c))}</td>`).join('')}</tr>`);
        i++;
      }
      const headerHtml = `<tr>${headerCells.map((c) => `<th>${renderInline(escapeHtml(c))}</th>`).join('')}</tr>`;
      htmlParts.push(`<table><thead>${headerHtml}</thead><tbody>${bodyRows.join('')}</tbody></table>`);
      continue;
    }

    // Plain paragraph - collect consecutive non-blank, non-special lines as one <p>.
    const paragraphLines: string[] = [];
    while (
      i < lines.length &&
      lines[i].trim() !== '' &&
      !lines[i].match(/^#{1,3}\s+/) &&
      !lines[i].startsWith('- ') &&
      !isTableRow(lines[i])
    ) {
      paragraphLines.push(renderInline(escapeHtml(lines[i])));
      i++;
    }
    htmlParts.push(`<p>${paragraphLines.join('<br>')}</p>`);
  }

  return htmlParts.join('\n');
}

/**
 * Wraps a rendered markdown fragment in a full HTML page, reusing the same base styling as the
 * pipelineReport dashboard (REPORT_PAGE_BASE_CSS) plus a few extras for article-style content
 * (headings below h1, tables, unordered lists) that the dashboard's card-grid layout doesn't need.
 *
 * backLabel defaults to this function's original, pipelineReport-specific text so every
 * pre-existing caller (cost/healing/flaky/traceability/promptVersions, via
 * pipelineReport.ts's writeSubReportPages()) is unaffected - pass an explicit label for any
 * back-link that doesn't actually point at the pipeline health dashboard (e.g. scrumDashboard.ts's
 * sub-report pages, which link back to the Scrum Dashboard instead).
 */
export function wrapReportPage(
  title: string,
  bodyHtml: string,
  backHref?: string,
  backLabel: string = 'Back to pipeline health dashboard',
): string {
  const backLink = backHref
    ? `<a class="back-link" href="${backHref.replace(/"/g, '&quot;')}">&larr; ${escapeHtml(backLabel)}</a>`
    : '';
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title.replace(/</g, '&lt;')}</title>
<style>
${REPORT_PAGE_BASE_CSS}
  article h1 { font-size: 20px; margin: 24px 0 8px; }
  article h1:first-child { margin-top: 0; }
  article h2 { font-size: 16px; margin: 20px 0 8px; }
  article h3 { font-size: 14px; margin: 16px 0 6px; color: var(--text-secondary); }
  article p { font-size: 14px; line-height: 1.6; margin: 0 0 10px; }
  article ul { margin: 0 0 14px; padding-left: 20px; font-size: 14px; line-height: 1.6; }
  article table { width: 100%; border-collapse: collapse; margin: 0 0 20px; font-size: 13px; }
  article th, article td { text-align: left; padding: 6px 10px; border-bottom: 1px solid var(--border); }
  article th { color: var(--text-secondary); font-weight: 600; }
</style>
</head>
<body>
<div class="wrap">
  ${backLink}
  <article>
${bodyHtml}
  </article>
</div>
</body>
</html>
`;
}
